Release version v1.0.1332
Metacello new
    baseline: 'GToolkitForPharo9';
    repository: 'github://feenkcom/gtoolkit:v1.0.1332/src';
    load

All commits (including upstream repositories) since last build:
https://github.com/feenkcom/gtoolkit-utility/commit/388440 by Alistair Grant
BaselineOfGToolkitUtility load GToolkit-Utility-Streams


https://github.com/feenkcom/gtoolkit-utility/commit/b8ebb1 by Alistair Grant
[feenkcom/gtoolkit#4188] Add ObjectMemoryByteReadStream


https://github.com/feenkcom/gtoolkit-pager/commit/c36e87 by Juraj Kubelka
add `GtPagerStep>>#setPageAt:widthInSpaceRatio:` [feenkcom/gtoolkit#4127]


https://github.com/feenkcom/gt4pharo/commit/0c10bf by Juraj Kubelka
set `selfObject` only for instance-side methods [feenkcom/gtoolkit#4127]


https://github.com/feenkcom/lepiter/commit/2ed536 by Alistair Grant
LeDuplicatePageIdError>>deletePageFile: remove halt.


https://github.com/feenkcom/lepiter/commit/6d24fb by Alistair Grant
LeJsonV4SerialisationExamples>>bitmap compare the deserialised object's class against the original.

Forms can have either a Bitmap or a ByteArray for their bits, so we can't check against the fixed class.


https://github.com/feenkcom/lepiter/commit/06154d by Alistair Grant
LeBinaryContentsHash class>>fromString: use ObjectMemoryByteReadStream to feed the hash.


https://github.com/feenkcom/lepiter/commit/f7e416 by Alistair Grant
LeDuplicatePageIdError: remove the page from the DB as well as deleting the underlying file.


https://github.com/feenkcom/gtoolkit-demos/commit/0cf816 by Juraj Kubelka
Merge 94f7a2f2714a04d77c214d95e1fb28484f77e444


https://github.com/feenkcom/gtoolkit-demos/commit/4986db by Juraj Kubelka
use `GtPagerStep>>#setPageAt:widthInSpaceRatio:` [feenkcom/gtoolkit#4127]


https://github.com/feenkcom/iceberg-git-cli/commit/67376b by Sven Van Caekenberghe
Add contrast color to PureGitAuthor and PureGitFile>>#computeAuthors


https://github.com/feenkcom/gt4git/commit/54af10 by Sven Van Caekenberghe
Fixed a typo in PureGitTrackedFile>>#gtViewGraphFor:


https://github.com/feenkcom/gt4git/commit/bc2760 by Sven Van Caekenberghe
Adapt PureGitTrackedFile>>#gtViewKumpelFor: to used shared authors and colors, add shift-click to inspect author of a tracked line


https://github.com/feenkcom/gt4git/commit/97d8fa by Sven Van Caekenberghe
Add contrast color to PureGitAuthor and use new accessors


https://github.com/feenkcom/gtoolkit-world/commit/025d34 by Juraj Kubelka
Display by-class and by-package views also in the binary filters [feenkcom/gtoolkit#4187]